// Auto-generated by safeword from SAFEWORD_SCHEMA. Do not edit by hand.
// Source: ownedFiles ∪ managedFiles ∪ jsonMerges ∪ textPatches → top-level prefixes.
// Regenerated on every `safeword setup` and `safeword upgrade`.

export const SAFEWORD_PATHS: readonly string[] = [
  '.claude/',
  '.cursor/',
  '.gitignore',
  '.golangci.yml',
  '.importlinter',
  '.jscpd.json',
  '.mcp.json',
  '.prettierignore',
  '.prettierrc',
  '.safeword-project/',
  '.safeword/',
  '.sqlfluff',
  'AGENTS.md',
  'biome.json',
  'biome.jsonc',
  'CLAUDE.md',
  'clippy.toml',
  'eslint.config.mjs',
  'knip.json',
  'mypy.ini',
  'package.json',
  'ruff.toml',
  'rustfmt.toml',
  'tsconfig.json',
];

/**
 * Match a file path against the safeword-managed set. Directory prefixes
 * (entries ending in `/`) match by `startsWith`; bare file paths must
 * match exactly so e.g. `package.json.bak` does not match `package.json`.
 */
export function isSafewordPath(file: string): boolean {
  for (const prefix of SAFEWORD_PATHS) {
    if (prefix.endsWith('/')) {
      if (file.startsWith(prefix)) return true;
    } else if (file === prefix) {
      return true;
    }
  }
  return false;
}

/**
 * Pick the safeword-managed subset of files reported by `git diff --name-only`
 * (changed) and `git ls-files --others --exclude-standard` (untracked).
 * Used by the auto-upgrade hook to decide what to stage after `safeword upgrade`.
 */
export function filterSafewordFiles(
  changedFiles: readonly string[],
  untrackedFiles: readonly string[],
): readonly string[] {
  return [...changedFiles, ...untrackedFiles].filter(f => isSafewordPath(f));
}
